[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/hien078/Machine-Learning-from-scratch/blob/master/topics/16_transformer/exercises.ipynb)

# Topic 16: Transformer Architecture — Exercises & Problem Set

**Author:** ML First Principles Series  
**Prerequisites:** Topic 16 Theory & First-Principles Notebook  

---

## Exercise 1: Scaled Dot-Product Attention (Hand Calculation)

Given Query matrix $Q \in \mathbb{R}^{2 \times 2}$ and Key matrix $K \in \mathbb{R}^{2 \times 2}$:

$$Q = \begin{pmatrix} 1 & 0 \\ 0 & 2 \end{pmatrix}, \quad K = \begin{pmatrix} 1 & 1 \\ 0 & 1 \end{pmatrix}$$

1. Compute the scaled attention scores $\frac{Q K^T}{\sqrt{d_k}}$ where $d_k = 2$.
2. Apply Softmax to compute the attention weight matrix $A$.

## Exercise 2: Causal Masking Implementation

Implement a function `apply_causal_mask(scores)` that takes a score matrix of shape `(batch, seq_len, seq_len)` and applies an upper-triangular mask with `-inf` values.

In [1]:
import numpy as np

def apply_causal_mask(scores):
    seq_len = scores.shape[-1]
    mask = np.triu(np.ones((seq_len, seq_len)), k=1).astype(bool)
    masked_scores = scores.copy()
    masked_scores[..., mask] = -1e9
    return masked_scores

# Test
scores = np.ones((1, 4, 4))
print(apply_causal_mask(scores))


[[[ 1.e+00 -1.e+09 -1.e+09 -1.e+09]
  [ 1.e+00  1.e+00 -1.e+09 -1.e+09]
  [ 1.e+00  1.e+00  1.e+00 -1.e+09]
  [ 1.e+00  1.e+00  1.e+00  1.e+00]]]
